/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaTicTacToe;

import JavaTicTacToe.Play.*;

public class App {

    public static void main(String[] args) {
      Play.go();
    }
}



