/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaTicTacToe;

import JavaTicTacToe.Output.*;
import JavaTicTacToe.Play.*;

public class App {

    public static void main(String[] args) {
        Output output = OutputFactory.createOutput(OutputTypes.CONSOLE);
        Play.go(output);
    }
}



