/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaTicTacToe;

import JavaTicTacToe.Game.*;
import JavaTicTacToe.Output.*;

public class App {

    public static void main(String[] args) {
        Output output = OutputFactory.createOutput(OutputTypes.CONSOLE);
        Game game = GameFactory.createGame(GameTypes.TWO_PLAYER, output);
        output.welcomesPlayer();
        game.play();
    }
}



